if(EXISTS "/home/paul/FH/embsys/embsw24/EmbSys/leapyear/leapyear/leapyear_test-b12d07c_tests.cmake")
  include("/home/paul/FH/embsys/embsw24/EmbSys/leapyear/leapyear/leapyear_test-b12d07c_tests.cmake")
else()
  add_test(leapyear_test_NOT_BUILT-b12d07c leapyear_test_NOT_BUILT-b12d07c)
endif()
